[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
presale_contract = "Gis8LkraTr9SZjcvU3xCwaSnhbmxAbvGMAqw7CYy7p4Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=27fd6baa-75e9-4d39-9832-d5a43419ad78"
wallet = "~/.config/solana/id.json"

[scripts]
addReferer = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/11-*.ts"
createAndBuy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/02-*.ts tests/03-*.ts tests/07-*.ts"
createAndStartAndBuy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/02-*.ts tests/03-*.ts tests/06-*.ts tests/07-*sol.ts"
createAndStartPresale = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/02-*.ts tests/03-*.ts tests/06-*.ts"
createDepositStartPresale = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/02-*.ts tests/03-*.ts tests/05-*.ts tests/06-*.ts tests/07-*sol.ts"
createDepositStartPresaleToken = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/02-*.ts tests/03-*.ts tests/05-*.ts tests/06-*.ts tests/07-*token.ts"
createPresale = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/02-*.ts tests/03-*.ts"
mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/02-*.ts"
testReferers = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/12-*.ts"
withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/02-*.ts tests/03-*.ts tests/05-*.ts tests/06-*.ts tests/07-*token.ts tests/10-*.ts tests/09-*.ts"
